[target.xtensa-esp32-none-elf]
image = "rustembedded/cross:xtensa-esp32-none-elf"
env = { volumes = ["IDF_PATH", "IDF_TOOLS_PATH"] }

[target.xtensa-esp8266-none-elf]
env = { volumes = ["IDF_PATH", "IDF_TOOLS_PATH"] }
